# Generated by Django 4.1 on 2022-08-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratos',
            options={},
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='CodigoContrato',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='Obsevaciones',
        ),
        migrations.AddField(
            model_name='contratos',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='CUP',
            field=models.FloatField(),
        ),
    ]
