# Generated by Django 4.0.6 on 2022-09-13 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0002_alter_contratos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='CUP',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='Creado',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='Modificado',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='Objeto',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='Titulo',
        ),
        migrations.AddField(
            model_name='contratos',
            name='cliente',
            field=models.CharField(default=1, max_length=200, verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratos',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Importe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratos',
            name='numero',
            field=models.CharField(default=1, max_length=30, unique=True, verbose_name='Número'),
            preserve_default=False,
        ),
    ]
