# Generated by Django 4.1 on 2022-09-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0003_remove_contratos_cup_remove_contratos_creado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='titulo',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulo'),
        ),
    ]
