# Generated by Django 4.1 on 2022-09-14 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0004_contratos_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratos',
            options={'verbose_name': 'contrato', 'verbose_name_plural': 'contratos'},
        ),
    ]
