# Generated by Django 4.1 on 2022-09-23 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0007_organismo_remove_contratos_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='entidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Contratos.organismo'),
        ),
    ]
