# Generated by Django 4.1 on 2022-09-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0008_contratos_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
