# Generated by Django 4.1 on 2022-09-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0009_alter_contratos_aprobado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='entidad',
        ),
        migrations.DeleteModel(
            name='Organismo',
        ),
    ]
